var form = document.querySelector('form')
var gradeForm = new GradeForm(form)
var header = document.querySelector('header')
var pageheader = new PageHeader(header)
var tableElement = document.querySelector('table')
var gradeTable = new GradeTable(tableElement)
var app = new App(gradeTable,pageheader,gradeForm)
app.start()
