var header = document.querySelector('header')
var pageheader = new PageHeader(header)
var tableElement = document.querySelector('table')
var gradeTable = new GradeTable(tableElement)
var app = new App(gradeTable,pageheader)
app.start()
