
const form = document.querySelector('form')
const gradeForm = new GradeForm(form)
const header = document.querySelector('header')
const pageheader = new PageHeader(header)
const tableElement = document.querySelector('table')
const pElement = document.querySelector('p')
const gradeTable = new GradeTable(tableElement,pElement)
const app = new App(gradeTable,pageheader,gradeForm)
app.start()
